Bug fix

diff --git a/.github/workflows/pester.yml b/.github/workflows/pester.yml
--- a/.github/workflows/pester.yml
+++ b/.github/workflows/pester.yml
@@ -1,12 +1,32 @@
 name: Pester
 on:
+  push:
+    branches: [ main ]
   pull_request:
     branches: [ main ]
 jobs:
-  publish-module:
-    runs-on: ubuntu-latest
+  test-pwsh:
+    strategy:
+      matrix:
+        platform: [ubuntu-latest, macos-latest, windows-latest]
+    runs-on: ${{ matrix.platform }}
     steps:
     - uses: actions/checkout@v1
-    - name: Publish-Module
-      run: Publish-Module -Path .\module\ -NuGetApiKey ${{ secrets.POWERSHELLGALLERY }}
+    - name: Run Pester tests (pwsh)
+      run: |
+        Set-PSRepository psgallery -InstallationPolicy trusted
+        Install-Module -Name Pester -RequiredVersion 5.0.4 -Force;
+        Invoke-Pester -Path "tests";
+      
       shell: pwsh
+  
+  test-posh:
+    runs-on: windows-latest
+    steps:
+    - uses: actions/checkout@v1
+    - name: Run Pester tests (PowerShell)
+      run: |
+        Set-PSRepository psgallery -InstallationPolicy trusted
+        Install-Module -Name Pester -RequiredVersion 5.0.4 -Force;
+        Invoke-Pester -Path "tests";
+        if ($Error[0].Fullyqualifiederrorid -eq 'PesterAssertionFailed') {exit 1};
